import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"

import { settleAuthoritativeRound } from "../lib/authoritative-settlement.ts"

function sequence(values) {
  let index = 0
  return (max) => {
    const value = values[index++]
    assert.ok(Number.isInteger(value) && value >= 0 && value < max)
    return value
  }
}

test("baccarat ignores client outcomes and calculates from canonical bets", () => {
  const result = settleAuthoritativeRound(
    "baccarat",
    { bets: { player: 10, banker: 0, tie: 0, playerPair: 0, bankerPair: 0 } },
    sequence([9, 0, 1, 1]),
  )

  assert.equal(result.outcome, "win")
  assert.equal(result.delta, 10)
  assert.equal(result.totalStake, 10)
  assert.equal(result.resultSnapshot.winner, "P")
})

test("dice uses server RNG and fixed server payouts", () => {
  const result = settleAuthoritativeRound(
    "dice",
    { bets: { big: 10, triple: 10 } },
    sequence([0, 0, 0]),
  )

  assert.deepEqual(result.resultSnapshot.dice, [1, 1, 1])
  assert.equal(result.delta, 230)
  assert.equal(result.totalStake, 20)
})

test("roulette ignores forged numbers and payout fields", () => {
  const result = settleAuthoritativeRound(
    "roulette",
    { bets: [{ key: "straight:1", amount: 10, numbers: [1, 2, 3], payout: 999999 }] },
    sequence([1]),
  )

  assert.equal(result.delta, 350)
  assert.deepEqual(result.betSnapshot.bets, [{ key: "straight:1", amount: 10 }])
})

test("roulette rejects an unknown forged bet", () => {
  assert.throws(
    () => settleAuthoritativeRound(
      "roulette",
      { bets: [{ key: "forged:any-number", amount: 1000000, payout: 1000000 }] },
      sequence([1]),
    ),
    /valid bet/i,
  )
})

test("blackjack outcome and payout are generated by the server", () => {
  const result = settleAuthoritativeRound(
    "blackjack",
    { hands: [{ bet: 10 }] },
    sequence([9, 6, 9, 7]),
  )

  assert.equal(result.delta, 10)
  assert.equal(result.totalStake, 10)
  assert.equal(result.resultSnapshot.dealerTotal, 17)
})

test("client contracts and database migration close direct-write boundaries", async () => {
  const [roundClient, cashOutClient, memberData, migration] = await Promise.all([
    readFile(new URL("../lib/member-round-client.ts", import.meta.url), "utf8"),
    readFile(new URL("../lib/table-session-client.ts", import.meta.url), "utf8"),
    readFile(new URL("../lib/member-data.ts", import.meta.url), "utf8"),
    readFile(new URL("../supabase/migrations/20260610160000_authoritative_settlement_boundary.sql", import.meta.url), "utf8"),
  ])

  for (const forbidden of ["outcome:", "delta:", "bankroll:", "resultSnapshot:"]) {
    assert.equal(roundClient.includes(forbidden), false)
  }
  assert.equal(cashOutClient.includes("expectedChipBalance"), false)
  assert.equal(memberData.includes("patchBody.expectedChipBalance"), false)
  assert.equal(memberData.includes("patchBody.delta"), false)
  assert.equal(memberData.includes("patchBody.outcome"), false)
  assert.match(migration, /normalized_stake <= 0 or normalized_stake > balance_before/)
  assert.match(migration, /revoke insert, update on table public\.member_game_progress from authenticated/)
  assert.match(migration, /revoke insert on table public\.member_events from authenticated/)
})
