create table if not exists public.api_rate_limit_buckets (
  action text not null,
  key_hash text not null,
  window_started_at timestamptz not null,
  request_count integer not null default 0 check (request_count >= 0),
  expires_at timestamptz not null,
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (action, key_hash, window_started_at)
);

create index if not exists api_rate_limit_buckets_expires_at_idx
on public.api_rate_limit_buckets (expires_at);

create table if not exists public.security_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  action text not null,
  result text not null,
  key_hash text,
  user_id uuid,
  request_id text not null,
  reason text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists security_events_created_at_idx
on public.security_events (created_at desc);

create index if not exists security_events_action_created_at_idx
on public.security_events (action, created_at desc);

alter table public.api_rate_limit_buckets enable row level security;
alter table public.security_events enable row level security;

revoke all on table public.api_rate_limit_buckets from public, anon, authenticated;
revoke all on table public.security_events from public, anon, authenticated;
grant select, insert, update, delete on table public.api_rate_limit_buckets to service_role;
grant select, insert on table public.security_events to service_role;
grant usage, select on sequence public.security_events_id_seq to service_role;

create or replace function public.consume_api_rate_limit(
  p_action text,
  p_key_hash text,
  p_limit integer,
  p_window_seconds integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := now();
  window_start timestamptz;
  bucket public.api_rate_limit_buckets%rowtype;
  retry_after integer;
begin
  if coalesce(nullif(p_action, ''), '') = ''
    or coalesce(nullif(p_key_hash, ''), '') = ''
    or p_limit < 1
    or p_window_seconds < 1 then
    raise exception 'A valid rate limit action, key, limit, and window are required.' using errcode = '22023';
  end if;

  window_start := to_timestamp(
    floor(extract(epoch from current_time) / p_window_seconds) * p_window_seconds
  );

  insert into public.api_rate_limit_buckets (
    action,
    key_hash,
    window_started_at,
    request_count,
    expires_at,
    updated_at
  )
  values (
    left(p_action, 120),
    left(p_key_hash, 128),
    window_start,
    1,
    window_start + make_interval(secs => p_window_seconds),
    v_now
  )
  on conflict (action, key_hash, window_started_at) do update
  set request_count = public.api_rate_limit_buckets.request_count + 1,
      expires_at = excluded.expires_at,
      updated_at = v_now
  returning * into bucket;

  retry_after := greatest(1, ceil(extract(epoch from bucket.expires_at - v_now))::integer);

  return jsonb_build_object(
    'allowed', bucket.request_count <= p_limit,
    'count', bucket.request_count,
    'limit', p_limit,
    'retry_after', retry_after,
    'window_started_at', bucket.window_started_at,
    'expires_at', bucket.expires_at
  );
end;
$$;

create or replace function public.record_security_event(
  p_action text,
  p_result text,
  p_key_hash text,
  p_request_id text,
  p_reason text default null,
  p_user_id uuid default null,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.security_events (
    action,
    result,
    key_hash,
    user_id,
    request_id,
    reason,
    metadata
  )
  values (
    left(p_action, 120),
    left(p_result, 40),
    left(p_key_hash, 128),
    p_user_id,
    left(p_request_id, 120),
    left(p_reason, 280),
    coalesce(p_metadata, '{}'::jsonb)
  );
end;
$$;

create or replace function public.cleanup_api_abuse_protection(
  p_security_event_retention_days integer default 90
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_buckets integer;
  deleted_events integer;
begin
  delete from public.api_rate_limit_buckets
  where expires_at < timezone('utc', now()) - interval '1 day';
  get diagnostics deleted_buckets = row_count;

  delete from public.security_events
  where created_at < timezone('utc', now()) - make_interval(days => greatest(1, p_security_event_retention_days));
  get diagnostics deleted_events = row_count;

  return jsonb_build_object(
    'deleted_buckets', deleted_buckets,
    'deleted_events', deleted_events
  );
end;
$$;

revoke execute on function public.consume_api_rate_limit(text, text, integer, integer) from public, anon, authenticated;
revoke execute on function public.record_security_event(text, text, text, text, text, uuid, jsonb) from public, anon, authenticated;
revoke execute on function public.cleanup_api_abuse_protection(integer) from public, anon, authenticated;

grant execute on function public.consume_api_rate_limit(text, text, integer, integer) to service_role;
grant execute on function public.record_security_event(text, text, text, text, text, uuid, jsonb) to service_role;
grant execute on function public.cleanup_api_abuse_protection(integer) to service_role;
