create table if not exists public.member_consents (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  terms_version text not null,
  privacy_version text not null,
  age_attestation_version text not null,
  age_attested boolean not null check (age_attested),
  locale text not null default 'en',
  accepted_at timestamptz not null default now(),
  source text not null default 'registration'
);

create unique index if not exists member_consents_user_versions_idx
on public.member_consents (user_id, terms_version, privacy_version, age_attestation_version);

create index if not exists member_consents_user_accepted_at_idx
on public.member_consents (user_id, accepted_at desc);

create table if not exists public.account_deletion_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  status text not null default 'requested'
    check (status in ('requested', 'confirmed', 'canceled', 'completed', 'rejected')),
  requested_at timestamptz not null default now(),
  confirmed_at timestamptz,
  canceled_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  request_reason text,
  review_note text,
  metadata jsonb not null default '{}'::jsonb
);

create unique index if not exists account_deletion_requests_one_open_idx
on public.account_deletion_requests (user_id)
where status in ('requested', 'confirmed');

create index if not exists account_deletion_requests_user_updated_at_idx
on public.account_deletion_requests (user_id, updated_at desc);

alter table public.member_consents enable row level security;
alter table public.account_deletion_requests enable row level security;

revoke all on table public.member_consents from public, anon, authenticated;
revoke all on table public.account_deletion_requests from public, anon, authenticated;
grant select, insert on table public.member_consents to service_role;
grant select, insert, update on table public.account_deletion_requests to service_role;
grant usage, select on sequence public.member_consents_id_seq to service_role;

create or replace function public.handle_new_member_data()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.member_settings (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  insert into public.member_wallets (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  if coalesce((new.raw_user_meta_data ->> 'age_attested')::boolean, false)
    and coalesce(new.raw_user_meta_data ->> 'terms_version', '') <> ''
    and coalesce(new.raw_user_meta_data ->> 'privacy_version', '') <> ''
    and coalesce(new.raw_user_meta_data ->> 'age_attestation_version', '') <> '' then
    insert into public.member_consents (
      user_id,
      terms_version,
      privacy_version,
      age_attestation_version,
      age_attested,
      locale,
      source
    )
    values (
      new.id,
      new.raw_user_meta_data ->> 'terms_version',
      new.raw_user_meta_data ->> 'privacy_version',
      new.raw_user_meta_data ->> 'age_attestation_version',
      true,
      left(coalesce(new.raw_user_meta_data ->> 'locale', 'en'), 20),
      'registration'
    )
    on conflict (user_id, terms_version, privacy_version, age_attestation_version) do nothing;
  end if;

  return new;
end;
$$;

create or replace function public.set_account_deletion_request_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_account_deletion_request_updated_at on public.account_deletion_requests;
create trigger set_account_deletion_request_updated_at
before update on public.account_deletion_requests
for each row execute function public.set_account_deletion_request_updated_at();

revoke execute on function public.set_account_deletion_request_updated_at() from public, anon, authenticated;
